# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20190104_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
